// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EqoKV3C443PQ4h7jCRbOwI8aH1hKUds',
    appId: '1:105493903957:android:8222e1d470c1ea55c1f2dc',
    messagingSenderId: '105493903957',
    projectId: 'time-tracker-672cc',
    storageBucket: 'time-tracker-672cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1J0yCTzXHOa4tuhwvaEf3DU--oR5-So',
    appId: '1:105493903957:ios:bdf36d2ca79d66e6c1f2dc',
    messagingSenderId: '105493903957',
    projectId: 'time-tracker-672cc',
    storageBucket: 'time-tracker-672cc.firebasestorage.app',
    iosBundleId: 'com.time.tracker.j',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1J0yCTzXHOa4tuhwvaEf3DU--oR5-So',
    appId: '1:105493903957:ios:d281aabed95f5528c1f2dc',
    messagingSenderId: '105493903957',
    projectId: 'time-tracker-672cc',
    storageBucket: 'time-tracker-672cc.firebasestorage.app',
    iosBundleId: 'com.example.trackingModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvXbdpRwd1j0QdUZQc4JfcaCTH-lupzU',
    appId: '1:105493903957:web:d0a4088c8bcc94c1c1f2dc',
    messagingSenderId: '105493903957',
    projectId: 'time-tracker-672cc',
    authDomain: 'time-tracker-672cc.firebaseapp.com',
    storageBucket: 'time-tracker-672cc.firebasestorage.app',
    measurementId: 'G-X1SCG83JSG',
  );
}
