name: Geo_Pulse CI/CD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
     
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      -  name: Setup Java
         uses: actions/setup-java@v4
         with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Set Up Flutter    
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.4
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.4          

      # Recreate the firebase.json file
      - name: Create firebase.json
        run:  echo "${{ secrets.FIREBASE_JSON }}" | base64 -d > firebase.json
      # Recreate the firebase_options.json file
      - name: Create firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_DART }}" | base64 -d > lib/firebase_options.dart

      # Recreate the google-services.json file for Android
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json

      # If you have an additional Dart config file
      - name: Create secret.dart
        run: echo "${{ secrets.SECRET_DART }}" | base64 -d > lib/geo_pulse/features/notification_service/services/secret.dart
      #- name: Test flutter app 
       # run: flutter test
        # build apk
      - name: Build APK
        run: flutter build apk --release

      - name: Build appBundle
        run: flutter build appbundle
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
                         
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
          tag: v1.0.0
          token: ${{secrets.github_token}}

      #- name: Setup Git
      #  run: |
      #    git config user.name "CI Bot"
      #    git config user.email "ci-bot@example.com"

      #- name: Fetch All Branches
      #  run: git fetch --all

            